main:
	@(ocamlopt -c -w -1..61 types.ml)
	@(ocamlopt -c -w -1..61 helper_functions.ml)
	@(ocamlopt -c -w -1..61 secd.ml)
	@(ocamlopt -c -w -1..61 krivine.ml)
clean:
	@(rm *.cmi)
	@(rm *.cmx)
	@(rm *.o)
